export 'package:soeviewmap/infrastructure/navigation/bindings/controllers/authentifikasi.controller.binding.dart'; 
export 'package:soeviewmap/infrastructure/navigation/bindings/controllers/log_bot.controller.binding.dart'; 
import 'package:get/get.dart';
import 'package:soeviewmap/presentation/screens.dart';
part 'balas.controller.binding.dart';
part 'dahsboard.controller.binding.dart';
part 'home.controller.binding.dart';
part 'review.controller.binding.dart';
part 'template.controller.binding.dart';