part 'user.profile.model.dart';
part 'review.model.dart';
part 'review.stats.model.dart';
part 'sentiment.analysis.model.dart';
part 'review.template.model.dart';
part 'bot.model.dart';
part 'bot.log.model.dart';
part 'api.response.list.model.dart';
part 'notification.model.dart';
